const enum Strings {
  signIn = 'Войти',
  signUp = 'Регистрация',
  signOut = 'Выйти',
  goBack = 'Назад',
  signUpNow = 'Зарегистрироваться',
  submit = 'Отправить',
  proceed = 'Перейти',
  createAccount = 'Создайте бесплатную учетную запись',
  signInText = 'Войдите в свою учетную запись',
  loading = 'Загрузка...',
  greetings = 'Добро пожаловать!',
  close = 'Закрыть',
  create = 'Создать',
  creating = 'Создаём',
  cancel = 'Отмена',
  rename = 'Переименовать',
  duplicate = 'Дублировать',
  delete = 'Удалить',
  dateChange = 'Дата изменения',
  dateCreation = 'Дата создания',
  save = 'Сохранить',
  saveLoading = 'Сохраняем',

  forgotPassword = 'Забыли пароль?',
  alreadyMember = 'Уже зарегистрированы?',
  notMember = 'Еще не зарегистрированы?',
  beforeRegistration = 'Регистрируясь, вы принимаете',
  privacyPolicy = '«Политику конфиденциальности»',
  incorrectUserPassword = 'Неверный пользователь и/или пароль',

  connectionCode = 'Код подключения',
  beforeConnect = 'Переходя на презентацию, вы принимаете',
  myPresentations = 'Мои презентации',
  noPresentation = 'Вы еще не создавали презентации',
  createPresentationDesc = 'Создайте первую интерактивную презентацию и работайте с вовлеченной аудиторией онлайн',
  templates = 'Шаблоны',
  help = 'Помощь',
  findPresentation = 'Найти презентацию',
  nothingFound = 'Ничего не найдено',
  createNewPresentation = 'Создать новую презентацию',
  createPresentation = 'Создать презентацию',
  enterName = 'Введите название',
  renamePresentation = 'Переименовать презентацию',

  placeholderSessionCode = 'Введите код подключения',
  placeholderNameInput = 'Введите Имя и Фамилию',
  placeholderEmailInput = 'Введите e-mail',
  placeholderCreatePasswordInput = 'Придумайте пароль',
  placeholderEnterPasswordInput = 'Введите пароль',

  error = 'Ошибка',
  errorPresentationCode = 'Вы ввели неверный код презентации',
  errorRequired = 'Заполните данные',
  errorName = 'Введены недопустимые символы',
  errorEmail = 'E-mail введен некорректно',
  errorPassword = 'Пароль должен содержать не менее 8 символов, в т.ч. цифру и спецсимвол  ! @ # $ % ^ & *',
  emailAlreadyExistsDatabase = 'Данный email уже существует в базе данных',
  tryAgainLater = 'Попробуйте позже.',
  inDevelopment = 'В разработке',
  inDevelopmentDesc = 'К сожалению, данная функция пока в разработке. Мы обязательно добавим эту функциональность в следующем обновлении.',

  home = 'Главная',
  settings = 'Настройки',
  presentation = 'Презентация',
  profile = 'Профиль',

  undefined = 'Undefined',
  yourSessionCode = 'Your session code is ',

  privacyPolicyUrl = 'сил моих больше нет подключать deep linking, памагити',
}

export default Strings;
